function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t229__list_item a[href='"+url+"']").addClass("t-active");$(".t229__list_item a[href='"+url+"/']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t229_checkAnchorLinks(recid){if($(window).width()>=960){var t229_navLinks=$("#rec"+recid+" .t229__list_item a:not(.tooltipstered)[href*='#']");if(t229_navLinks.length>0){t229_catchScroll(t229_navLinks)}}}
function t229_catchScroll(t229_navLinks){var t229_clickedSectionId=null,t229_sections=new Array(),t229_sectionIdTonavigationLink=[],t229_interval=100,t229_lastCall,t229_timeoutId;t229_navLinks=$(t229_navLinks.get().reverse());t229_navLinks.each(function(){var t229_cursection=t229_getSectionByHref($(this));if(typeof t229_cursection.attr("id")!="undefined"){t229_sections.push(t229_cursection)}
t229_sectionIdTonavigationLink[t229_cursection.attr("id")]=$(this)});t229_updateSectionsOffsets(t229_sections);t229_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t229_updateSectionsOffsets(t229_sections)},200));$('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(t229_sections)});setInterval(function(){t229_updateSectionsOffsets(t229_sections)},5000);t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId);t229_navLinks.click(function(){var t229_clickedSection=t229_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t229_clickedSection.attr("id")!="undefined"){t229_navLinks.removeClass('t-active');$(this).addClass('t-active');t229_clickedSectionId=t229_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t229_now=new Date().getTime();if(t229_lastCall&&t229_now<(t229_lastCall+t229_interval)){clearTimeout(t229_timeoutId);t229_timeoutId=setTimeout(function(){t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)},t229_interval-(t229_now-t229_lastCall))}else{t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)}})}
function t229_updateSectionsOffsets(sections){$(sections).each(function(){var t229_curSection=$(this);t229_curSection.attr("data-offset-top",t229_curSection.offset().top)})}
function t229_getSectionByHref(curlink){var t229_curLinkValue=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t229_curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t229_curLinkValue+"']")}}
function t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId){var t229_scrollPosition=$(window).scrollTop(),t229_valueToReturn=t229_clickedSectionId;if(t229_sections.length!=0&&t229_clickedSectionId==null&&t229_sections[t229_sections.length-1].attr("data-offset-top")>(t229_scrollPosition+300)){t229_navLinks.removeClass('t-active');return null}
$(t229_sections).each(function(e){var t229_curSection=$(this),t229_sectionTop=t229_curSection.attr("data-offset-top"),t229_id=t229_curSection.attr('id'),t229_navLink=t229_sectionIdTonavigationLink[t229_id];if(((t229_scrollPosition+300)>=t229_sectionTop)||(t229_sections[0].attr("id")==t229_id&&t229_scrollPosition>=$(document).height()-$(window).height())){if(t229_clickedSectionId==null&&!t229_navLink.hasClass('t-active')){t229_navLinks.removeClass('t-active');t229_navLink.addClass('t-active');t229_valueToReturn=null}else{if(t229_clickedSectionId!=null&&t229_id==t229_clickedSectionId){t229_valueToReturn=null}}
return!1}});return t229_valueToReturn}
function t229_setPath(pageid){}
function t229_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t229_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$("#rec"+recid+" .t229").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t229_changeBgOpacityMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll)}else{el.css("background-color",bgcolor)}})}}
function t331_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t331_showPopup(recid);t331_resizePopup(recid);e.preventDefault();if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t331_setHeight(recid){var el=$("#rec"+recid);var div=el.find(".t331__video-carier");var ratiowidth=div.attr("data-video-width");var ratioheight=div.attr("data-video-height");var ratio=ratioheight/ratiowidth;var height=div.width()*ratio;div.height(height);div.parent().height(height)}
function t331_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');var youtubeid=el.find(".t331__youtube").attr('data-content-popup-video-url-youtube');var videourl='https://www.youtube.com/embed/'+youtubeid;el.find(".t331__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t331__iframe\" width=\"100.5%\" height=\"100.5%\" src=\""+videourl+"?autoplay=1&rel=0\" frameborder=\"0\" allowfullscreen></iframe>");popup.css('display','block');t331_setHeight(recid);setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');$('body').addClass('t331__body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t331_popup_close(recid)}});el.find('.t-popup__close').click(function(e){t331_popup_close(recid)});$(document).keydown(function(e){if(e.keyCode==27){t331_popup_close(recid)}})}
function t331_popup_close(recid){$('body').removeClass('t-body_popupshowed');$('body').removeClass('t331__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');setTimeout(function(){$("#rec"+recid+" .t331__video-carier").html("");$('#rec'+recid+' .t-popup').not('.t-popup_show').css('display','none')},300)}
function t331_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height(),popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t331_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t409_unifyHeights(recid){if($(window).width()>=960){var el=$("#rec"+recid);var imgwidth=el.find(".t409__img").width();var imgwrapperwidth=el.find(".t409__imgwrapper").css("max-width");var imgwrapperwidthpx=parseInt(imgwrapperwidth,10);var margin=imgwrapperwidthpx-imgwidth;el.find(".t409__img").css("margin-left",margin)}}
t422_setHeight=function(recid){if($(window).width()>960){t422_checkEqualHeight(recid)}else{$('#rec'+recid+' .t422__img-mobile').height(200);$('#rec'+recid+' .t422__text').height('auto')}};t422_checkEqualHeight=function(recid){var t422__txtel=$('#rec'+recid+' .t422__text');var t422__imgel=$('#rec'+recid+' .t422__img');var t422__textwrapperel=$('#rec'+recid+' .t422__textwrapper');var t422__borderwidth=0;if(t422__txtel.css("border-top-width")&&t422__txtel.css("border-top-width")[1]!='p'){t422__borderwidth=+(t422__txtel.css("border-top-width")[0]+t422__txtel.css('border-top-width')[1])}else{if(t422__txtel.css("border-top-width"))
t422__borderwidth=+(t422__txtel.css("border-top-width")[0])}
if(t422__imgel.height()<(t422__textwrapperel.outerHeight()+t422__borderwidth*2)){t422__imgel.height(t422__textwrapperel.outerHeight()+t422__borderwidth*2)}else{if((t422__imgel.height()-t422__borderwidth*2)>t422__textwrapperel.outerHeight()){t422__textwrapperel.outerHeight(t422__imgel.height()-t422__borderwidth*2)}}}