function t390_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t390_closePopup()}});el.find('.t-popup__close').click(function(e){t390_closePopup()});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t390_closePopup()}})}
function t390_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t390_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t390_showPopup(recid);t390_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t452_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t466_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t466__item a[href='"+url+"']").addClass("t-active");$(".t466__item a[href='"+url+"/']").addClass("t-active");$(".t466__item a[href='"+pathname+"']").addClass("t-active");$(".t466__item a[href='/"+pathname+"']").addClass("t-active");$(".t466__item a[href='"+pathname+"/']").addClass("t-active");$(".t466__item a[href='/"+pathname+"/']").addClass("t-active")}
function t466_checkAnchorLinks(recid){if($(window).width()>=960){var t466_navLinks=$("#rec"+recid+" .t466__menu a:not(.tooltipstered)[href*='#']");if(t466_navLinks.length>0){t466_catchScroll(t466_navLinks)}}}
function t466_catchScroll(t466_navLinks){var t466_clickedSectionId=null,t466_sections=new Array(),t466_sectionIdTonavigationLink={},t466_interval=100,t466_lastCall,t466_timeoutId,t466_offsetTop=$(".t466").attr("data-offset-top");if(typeof t466_offsetTop=="undefined"){t466_offsetTop=0}
t466_navLinks=$(t466_navLinks.get().reverse());t466_navLinks.each(function(){var t466_cursection=t466_getSectionByHref($(this));if(typeof t466_cursection.attr("id")!="undefined"){t466_sections.push(t466_cursection)}
t466_sectionIdTonavigationLink[t466_cursection.attr("id")]=$(this)});t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop);t466_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t466_navLinks.removeClass('t-active');t466_sectionIdTonavigationLink[t466_getSectionByHref($(this)).attr("id")].addClass('t-active');t466_clickedSectionId=t466_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t466_now=new Date().getTime();if(t466_lastCall&&t466_now<(t466_lastCall+t466_interval)){clearTimeout(t466_timeoutId);t466_timeoutId=setTimeout(function(){t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)},t466_interval-(t466_now-t466_lastCall))}else{t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)}})}
function t466_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,offsetTop){var t466_scrollPosition=$(window).scrollTop(),t466_valueToReturn=t466_clickedSectionId;$(t466_sections).each(function(e){var t466_curSection=$(this),t466_sectionTop=t466_curSection.offset().top,t466_id=t466_curSection.attr('id'),t466_navLink=t466_sectionIdTonavigationLink[t466_id];if(t466_scrollPosition>=(t466_sectionTop-offsetTop)||(t466_sections[0].attr("id")==t466_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t466_clickedSectionId==null&&!t466_navLink.hasClass('t-active')){t466_navLinks.removeClass('t-active');t466_navLink.addClass('t-active');t466_valueToReturn=null}else{if(t466_clickedSectionId!=null&&t466_id==t466_clickedSectionId){t466_valueToReturn=null}}
return!1}});return t466_valueToReturn}
function t466_initMobileMenu(recid){var window_width=$(window).width();var el=$("#rec"+recid);if(980>window_width){el.find(".t466").each(function(){$(this).find(".t466__mobile").css("top",$(this).find(".t466__container__bg_main").innerHeight()+2);$(this).find(".t466__burger, a[href*=#]").click(function(){if($(this).is(".tooltipstered, .t794__tm-link")){return}
$("body").toggleClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideToggle(300)})})}
$('.t466').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideUp(300)})}
function t466_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t466__beforeready')){el.removeClass('t466__beforeready')}}else{el.addClass('t466__beforeready')}}})}
function t466_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t774_init(recid){t774_unifyHeights(recid);$(window).bind('resize',t_throttle(function(){t774_unifyHeights(recid)},200));$(".t774").bind("displayChanged",function(){t774_unifyHeights(recid)});$(window).load(function(){t774_unifyHeights(recid)})}
function t774_unifyHeights(recid){var t774_el=$('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if($(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if($(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}
else{if($(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=$(this).find(".t774__textwrapper"),t774_curBtns=$(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t829_init(recid){var rec=$('#rec'+recid);var grid=rec.find('.t829__grid');var sizer=rec.find('.t829__grid-sizer');var item=rec.find('.t829__grid-item');var images=rec.find('.t829__grid img');var startContainerWidth=rec.find('.t829__grid-sizer').width();images.load(function(){if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_initMasonry(rec,recid,grid)}});if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_initMasonry(rec,recid,grid);t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}
grid.bind('touchmove scroll',function(){if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy=='y'){t_lazyload_update()}}})
$(window).bind('resize',function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}});$('.t829').bind('displayChanged',function(){t829_initMasonry(rec,recid,grid);if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}})}
function t829_initMasonry(rec,recid,grid){var $grid=grid;var gutterSizerWidth=rec.find('.t829__gutter-sizer').width();var gutterElement=rec.find('.t829__gutter-sizer').width()==40?39:'#rec'+recid+' .t829__gutter-sizer';$grid.imagesLoaded(function(){$grid.masonry({itemSelector:'#rec'+recid+' .t829__grid-item',columnWidth:'#rec'+recid+' .t829__grid-sizer',gutter:gutterElement,isFitWidth:!0})})}
function t829_calcColumnWidth(rec,startcontainerwidth,grid,sizer,item){var containerWidth=rec.find('.t829__container').width();var sizerWidth=rec.find('.t829__grid-sizer').width();var itemWidth=rec.find('.t829__grid-item').width();var gutterSizerWidth=rec.find('.t829__gutter-sizer').width()==40?39:rec.find('.t829__gutter-sizer').width();var columnAmount=Math.round(containerWidth/startcontainerwidth);var newSizerWidth=((containerWidth-gutterSizerWidth*(columnAmount-1))/columnAmount);if(containerWidth>itemWidth){sizer.css('width',newSizerWidth);item.css('width',newSizerWidth)}else{grid.css('width','100%');sizer.css('width','100%');item.css('width','100%')}}